version: '3'

services:
  trojan:
      build: ./trojan
      ports:
        - "443:443"
      volumes:
        - ./trojan/config:/config
        - ./ssl:/ssl
        - ./trojan/wait_for_caddy.sh:/wait_for_caddy.sh
      links:
        - caddy:__DOCKER_CADDY__
      depends_on: 
        - caddy
      extra_hosts:
        - "host.docker.internal:host-gateway"

  caddy:
      image: caddy:latest
      ports:
        - "80:80"
      volumes:
        - ./wwwroot:/usr/src
        - ./caddy/Caddyfile:/etc/caddy/Caddyfile
        - ./ssl:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory
      extra_hosts:
              - "host.docker.internal:host-gateway"